config/routes.rb
Rails.application.routes.draw do

  resources :messages
  root 'messages#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
 before_action :find_message, only: [:show, :edit, :destroy, :update]
  def index
    @messages = Message.all.order("created_at DESC")
  end

  def new
    @message = Message.new
  end

  def show
  end

  def create
    @message = Message.new(message_params)

    if @message.save
      redirect_to root_path
    else
      render 'new'
  end
end

def edit
  @message = Message.find(params[:id])
end

def update
  if @message.update(message_params)
    redirect_to root_path
  else
    render 'edit'
end
end

def destroy
  @message.destroy
  redirect_to root_path
end



private


def message_params
  params.require(:message).permit(:title, :description)
end


def find_message
  @message = Message.find(params[:id])
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Espn</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/messages/edit.html.erb
<%= render 'form' %>

app/views/messages/index.html.erb
<% @messages.each do |message| %>
<div class="col-md-10 col-md-offset-1">
  <div class="message">
    <h2 class="message-title"><%= message.title %></h2>
    <%= link_to "Join Chat", message, class:"btn-custom"%>
  </div>
</div>
<%end %>
<%= link_to "Post Message", new_message_path %>

app/views/messages/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1 class="new-header-msg">Create New Message</h1>
  <%= render 'form'%>
</div>

app/views/messages/show.html.erb
<h1><%= @message.title %></h1>
<%= @message.description %>

<%= link_to "Back", root_path, class: "btn btn-default"%>
<%= link_to "Edit Message", edit_message_path %>
<%= link_to "Delete",message_path(@message), method: :delete, data:{confirm: "you wanna do this?"} %>